# Generated by Django 5.1.5 on 2025-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=14)),
                ('message', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'Aloqa',
            },
        ),
    ]
