# Generated by Django 5.1.5 on 2025-01-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
