# Generated by Django 5.1.5 on 2025-01-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0002_alter_contact_message_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Aloqalar'},
        ),
    ]
