# Generated by Django 5.1.5 on 2025-01-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0004_fastcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mahsulot',
            },
        ),
    ]
