# Generated by Django 5.1.5 on 2025-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='testimonials_photos/')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonal',
            },
        ),
    ]
