# Generated by Django 5.1.5 on 2025-01-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0006_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
    ]
