# Generated by Django 5.1.5 on 2025-01-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choco', '0007_remove_testimonial_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Fikrlar'},
        ),
    ]
